### PR TITLE
Add typings

### PR DESCRIPTION
**Pull request by melfa**

### CODE REVIEW

**Comment by gausby** [comment]
Hi Melfa! Thanks for the contribution.

I don't really use JavaScript anymore, would you like to take over the project?

**Comment by melfa** [comment]
Thank you, but i just using your project, have no idea about transliteration and so on.

**Comment by melfa** [comment]
Would you please publish changes to npm?

**Comment by gausby** [comment]
Sorry, as I said: I have not touched javascript for years.

I grand you the full permission to take over the code.

**Pull request merged**
